[project]
name = "starknet-service"
authors = ["StarkNet Service Team"]
description = "A decentralized service infrastructure for StarkNet ecosystem"
telemetry = false
requirements = []

[contracts.service-governance]
path = "contracts/service-governance.clar"
depends_on = []

[contracts.service-marketplace]
path = "contracts/service-marketplace.clar"
depends_on = []

[contracts.service-reputation]
path = "contracts/service-reputation.clar"
depends_on = []

[contracts.service-license]
path = "contracts/service-license.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
